### ISSUE TITLE
Support formatLocale and timeFormatLocale

### ISSUE THREAD

**Issue by jonmmease** [vega/vl-convert#133]
See https://github.com/altair-viz/altair/issues/3261.

We should support locale objects and also named locales from the d3-format and d3-time-format packages.  These probably become two additional arguments to the `vega_to_*` and `vegalite_to_*` functions. When Altair calls vl-convert, it would propagate these from `alt.renderers.set_embed_options`.

@mattijn @MarcoBaroncini, do we want Altair to support setting locales based on their d3-format/d3-time-format names (e.g. `it-IT`)? vl-convert could bundle d3-format and d3-time-format and provide a Python to return the format objects so that Altair could accept the format file names as arguments to `alt.renderers.set_embed_options`.

**Comment by mattijn** [comment]
I think it that would be great if the locale name is recognized by its language-territory code set. 
It seems like a great option if that can be accomplished by bundling d3-format/d3-time-format).
One question, would it still be possible to use a custom `dict` for other variants not included in the d3-format/d3-time-format packages?

**Comment by jonmmease** [comment]
> One question, would it still be possible to use a custom dict for other variants not included in the d3-format/d3-time-format packages?

Yeah, an object could be provided as well

**Comment by mattijn** [comment]
Just wondering, is https://github.com/vega/vega-embed/issues/87 also of relevance here?
