### ISSUE TITLE
embed_options in mimebundle is NoneType (error when calling chart.save in Altair to a PDF)

### ISSUE THREAD

**Issue by jowens** [vega/vl-convert#159]
Having trouble interpreting the error message when calling `chart.save` to a PDF.

```
    chart.save(os.path.join(outputdir, title + ".pdf"), engine="vl-convert")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/altair/vegalite/v5/api.py", line 1214, in save
    save(**kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/altair/utils/save.py", line 200, in save
    perform_save()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/altair/utils/save.py", line 162, in perform_save
    mimebundle = spec_to_mimebundle(
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/altair/utils/mimebundle.py", line 77, in spec_to_mimebundle
    embed_options = preprocess_embed_options(embed_options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/altair/utils/mimebundle.py", line 321, in preprocess_embed_options
    embed_options = embed_options.copy()
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'
```

I have `import vl_convert as vlc` (although no other references to vlc in my code) and I've done `pip install vl-convert-python` but there's nothing in that trace that indicates it's dropped out of Altair into vl_convert. The Altair instructions are dead simple (https://altair-viz.github.io/user_guide/saving_charts.html) so I've clearly missed something.

Keeping you busy today!

**Comment by jonmmease** [comment]
Hey @jowens, you don't have to import `vl_convert` for this to work. This error is in Altair before it gets to invoking vl-convert.  Can you open an issue in the altair repo (https://github.com/altair-viz/altair) with a repro and the exact version of altair you're using?

I can't reproduce this with a simple test, and looking at the code in https://github.com/altair-viz/altair/blob/v5.2.0/altair/utils/mimebundle.py, it doesn't look like `embed_options` should ever be `None` when passed into `preprocess_embed_options`.

One quick thing to look at is, what's the result of?
```python
import altair as alt
alt.renderers.options.get("embed_options", {})
```
Could you include this result in the Altair issue?

**Comment by jowens** [comment]
Hate to make your life harder, really I do.

```
print(alt.renderers.options.get("embed_options", {}))
vf.enable()
print(alt.renderers.options.get("embed_options", {}))
```

prints

```
{}
None
```

**Comment by jowens** [comment]
Oh wait that's vegafusion. That's not you.

**Comment by jowens** [comment]
I've disabled vf and everything works as expected.

**Comment by jonmmease** [comment]
Oh, that's really helpful!  I'll open a VegaFusion issue to avoid setting this to None.
