### ISSUE TITLE
FontSize = 0 issue vlc.vegalite_to_svg()

### ISSUE THREAD

**Issue by michaelzwong** [vega/vl-convert#172]
I encountered an error when converting spec to svg with axes that have labelFontSize = 0. The error message indicates that there was a failure to locate text within an empty SVG element

`vlc.vegalite_to_svg(vl_spec=vl_spec)`

```
ERROR Error: Failed to locate text in SVG:

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100" height="100">
    <text x="20" y="50" font-size="0" font-family="sans-serif">000</text>
</svg>
```

```
{
  "layer": [
    {
      "encoding": {
        "x": {
          "axis": {
            "labelFontSize": 0
          }
        },
        "y": {
          "axis": {
            "labelFontSize": 0
          }
        }
      }
    }
  ]
}
```

The workaround was to set `axis: { "labels": False, "labelFontSize": 10 }

**Comment by jonmmease** [comment]
Thanks for the report and workaround @michaelzwong, this is something that we should fix in vl-convert, so going to re-open the issue for tracking.
