### ISSUE TITLE
Some text collapse in json to svg conversion

### ISSUE THREAD

**Issue by luiscastro193** [vega/vl-convert#174]
For some reason, the attached chart transforms into the attached svg file. It seems like text placement is failing. Vega editor renders it properly.

[P07.json](https://github.com/user-attachments/files/16367233/P07.json)
![P07](https://github.com/user-attachments/assets/69077b5c-ec61-4085-9aa4-0e63139a0aa2)

I also tried with a basic example chart and it worked fine though.

**Comment by jonmmease** [comment]
Thanks for the report @luiscastro193, it does look like something is going wrong with our text measurements. Nothing is obviously unusual about the characters used in the legend titles.

I'll try to take a look soon!

**Comment by jonmmease** [comment]
fixed in 1.5.1
