### ISSUE TITLE
vl-convert fails to load

### ISSUE THREAD

**Issue by ganong123** [vega/vl-convert#183]
Problem: installed package will not load. Please let me know if you need additional information!

### procedure

Installation via terminal
```
(.venv) peterganong@HPP-GANONG issue_7_viz_lec % pip install vl-convert-python 

Collecting vl-convert-python
  Using cached vl_convert_python-1.6.0-cp37-abi3-macosx_10_12_x86_64.whl.metadata (5.2 kB)
Using cached vl_convert_python-1.6.0-cp37-abi3-macosx_10_12_x86_64.whl (27.6 MB)
Installing collected packages: vl-convert-python
Successfully installed vl-convert-python-1.6.0
```

Python interpreter: `import vl_convert`

### output
```
{
	"name": "ImportError",
	"message": "dlopen(/Users/peterganong/repo/fall2024/issue_7_viz_lec/.venv/lib/python3.12/site-packages/vl_convert/vl_convert.abi3.so, 0x0002): symbol not found in flat namespace '_PyPyBool_Type'",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File /Users/peterganong/repo/fall2024/issue_7_viz_lec/test.qmd:1
----> 1 import vl_convert

File ~/repo/fall2024/issue_7_viz_lec/.venv/lib/python3.12/site-packages/vl_convert/__init__.py:1
----> 1 from .vl_convert import *
      3 __doc__ = vl_convert.__doc__
      4 if hasattr(vl_convert, \"__all__\"):

ImportError: dlopen(/Users/peterganong/repo/fall2024/issue_7_viz_lec/.venv/lib/python3.12/site-packages/vl_convert/vl_convert.abi3.so, 0x0002): symbol not found in flat namespace '_PyPyBool_Type'"
}
```

**Comment by jonmmease** [comment]
thanks for the report, I think I may have messed up the intel mac package when GitHub Actions changed the default mac image. I don't have access to an intel mac at the moment, are you willing to try installing a dev wheel (already built) when I have time to work on this?

**Comment by ganong123** [comment]
Yes I would be glad to!

**Comment by jonmmease** [comment]
Should be fixed in 1.6.1. Let me know if you still see any issues

**Comment by ForceBru** [comment]
@jonmmease, I'm getting the exact same issue on 1.6.1:

```
$ uv venv && uv pip install vl-convert-python
Using CPython 3.12.1 interpreter at: /Users/forcebru/.pyenv/versions/3.12.1/bin/python
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate.fish
Resolved 1 package in 2ms
Installed 1 package in 31ms
 + vl-convert-python==1.6.1
$ source .venv/bin/activate.fish
$ python -c "import vl_convert"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/forcebru/test/test-vl/.venv/lib/python3.12/site-packages/vl_convert/__init__.py", line 1, in <module>
    from .vl_convert import *
ImportError: dlopen(/Users/forcebru/test/test-vl/.venv/lib/python3.12/site-packages/vl_convert/vl_convert.abi3.so, 0x0002): symbol not found in flat namespace '_PyPyBool_Type'
$
```

**Comment by ganong123** [comment]
@jonmmease thanks for trying to resolve this! I upgraded to 1.6.1 but am getting the same issue as with 1.6.0. 

If you link to a wheel I am happy to give that a shot.

Apple M1 Pro with Sonoma 14.6.1

**Comment by jonmmease** [comment]
@ganong123, have you been on an arm MacOS machine the whole time? Based on the original error message I thought you were on an intel machine.

Could @ganong123 and @ForceBru both try to direct install the wheels from the release artifacts? https://github.com/vega/vl-convert/releases/tag/v1.6.1

Also @ForceBru, I'd like to confirm which wheel file is installed when you run `uv pip install`. Could you look into whether there is a verbose mode that would display the full name of the wheel file that gets installed?

**Comment by ganong123** [comment]
@jonmmease thanks for your help!

Here is what I get when I try to install the wheel, let me know if I should be trying something else instead!

```
(.venv) peterganong@HPP-GANONG lectures_full % pip install ~/downloads2/vl_convert_python-1.6.1-cp37-abi3-macosx_11_0_arm64.whl
ERROR: vl_convert_python-1.6.1-cp37-abi3-macosx_11_0_arm64.whl is not a supported wheel on this platform.
```

I apologize for the confusion about what type of processor I have. my initial post was silent on this. then your reply mentioned intel, but I didn't notice that when I replied.

**Comment by jonmmease** [comment]
Thanks for the additional details @ganong123, it looks like you may have installed an intel version of Python, which then runs using [Rosetta 2](https://support.apple.com/en-us/102527) emulation.

To check, try running this:

```
python -c "import platform; print(platform.machine())"
```

On my Python installation on an M1, this returns

```
arm64
```

It's possible that vl-convert is not working under Rosetta. Would installing an arm version of Python be an option for you?

**Comment by jonmmease** [comment]
Oh, actualy, both of your error messages refer to `_PyPyBool_Type`, which implies that you're running the [PyPy](https://pypy.org/) Python interpreter (rather than the standard CPython implementation).

Run this from within the virtual environment to double check:

```
python -c "import sys; print(sys.implementation.name)"
```

We're not currently building wheels for PyPy, but that's something we could look into.

**Comment by ForceBru** [comment]
@jonmmease, I'm not using PyPy (it's indeed strange that the error message talks about PyPy):

```
$ python -c "import sys; print(sys.implementation.name)"
cpython
```

Verbose installation output:

```
$ uv pip install --verbose vl-convert-python
DEBUG uv 0.4.17
DEBUG Searching for default Python interpreter in system path
DEBUG Found `cpython-3.12.1-macos-x86_64-none` at `/Users/forcebru/test/test-vl/.venv/bin/python3` (active virtual environment)
DEBUG Using Python 3.12.1 environment at .venv/bin/python3
DEBUG Acquired lock for `.venv`
DEBUG At least one requirement is not satisfied: vl-convert-python
DEBUG Using request timeout of 30s
DEBUG Solving with installed Python version: 3.12.1
DEBUG Solving with target Python version: >=3.12.1
DEBUG Adding direct dependency: vl-convert-python*
DEBUG Found fresh response for: https://pypi.org/simple/vl-convert-python/
DEBUG Searching for a compatible version of vl-convert-python (*)
DEBUG Selecting: vl-convert-python==1.6.1 [compatible] (vl_convert_python-1.6.1-cp37-abi3-macosx_10_12_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/ba/9a/476a51dc05cac44ebf4fc88eb19571c02b65b416a102830a44bccac2e2cd/vl_convert_python-1.6.1-cp37-abi3-macosx_10_12_x86_64.whl.metadata
DEBUG Tried 1 versions: vl-convert-python 1
DEBUG Split specific environment resolution took 0.002s
Resolved 1 package in 3ms
DEBUG Requirement already cached: vl-convert-python==1.6.1
Installed 1 package in 2ms
 + vl-convert-python==1.6.1
DEBUG Released lock at `/Users/forcebru/test/test-vl/.venv/.lock`
$ python -c "import vl_convert"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/forcebru/test/test-vl/.venv/lib/python3.12/site-packages/vl_convert/__init__.py", line 1, in <module>
    from .vl_convert import *
ImportError: dlopen(/Users/forcebru/test/test-vl/.venv/lib/python3.12/site-packages/vl_convert/vl_convert.abi3.so, 0x0002): symbol not found in flat namespace '_PyPyBool_Type'
```

**Comment by jonmmease** [comment]
Hmm, I'm not sure what's going on here. PyO3 has one reference to `PyPyBool_Type`, but it's only used on windows when targeting PyPy.

https://github.com/PyO3/pyo3/blob/2fa97f907a2b1ecad4d1a9bb254246540cf1d1dc/pyo3-ffi/src/object.rs#L192-L198

I'll try to dust off an old intel mac laptop to see if I can reproduce this

**Comment by jonmmease** [comment]
I reproduced this on my intel mac laptop, and was able to fix it with a build tweak.

Could you try the intel wheel from this archive? https://github.com/vega/vl-convert/actions/runs/11163301956/artifacts/2011729268

The version number is the same as the latest release, so make sure to uninstall the current version first.

**Comment by jonmmease** [comment]
These changes were released in 1.70.0, please give this a reversion a try and let me know how it goes.

**Comment by ForceBru** [comment]
Yes, 1.70.0 seems to work fine for me: I was able to import it and save a few Altair plots as SVG and PNG. Thank you!

**Comment by jonmmease** [comment]
Great, thanks for giving it a try @ForceBru.

@ganong123 could you confirm whether this works for you as well?

**Comment by ganong123** [comment]
The fix works for me -- thank you so much!
