### ISSUE TITLE
Improve contributing/dev setup guide

### ISSUE THREAD

**Issue by dangotbanned** [vega/vl-convert#186]
While I was working on #185 I noticed that [vl-convert-python#development-setup](https://github.com/vega/vl-convert/tree/main/vl-convert-python#development-setup) mentions using `conda` for an env.

I thought this was strange as the `.gitignore` seems to imply there may be a [`pixi`](https://pixi.sh/latest/switching_from/conda/#environment-vs-project) config in-use.

https://github.com/vega/vl-convert/blob/8f5200cf6d92d8cf712fe097d128b8f1d7b48a88/.gitignore#L17-L21

I'm curious about contributing more in the future, and a project-style config/setup guide would be super helpful in making sure everything is set up correctly. 

@jonmmease are you using `pixi`?

From my understanding, `hatch` (used in https://github.com/vega/altair and https://github.com/vega/sphinxext-altair) wouldn't be a good fit due to non-`python` dependencies.

# Side note
Not everything from there is transferable, but I used parts of https://docs.pola.rs/development/contributing/#setting-up-your-local-environment to help with setting up the `rust` side of things.
Maybe there are parts of that guide that could be drawn from?

**Comment by jonmmease** [comment]
Hi @dangotbanned, I'm using pixi locally and would like use it officially here as I do in VegaFusion.

A nice thing about using pixi is that we can install Rust inside the environment, so that it's not necessary to have a system installation of Rust.

**Comment by dangotbanned** [comment]
> Hi @dangotbanned, I'm using pixi locally and would like use it officially here as I do in VegaFusion.
> 
> A nice thing about using pixi is that we can install Rust inside the environment, so that it's not necessary to have a system installation of Rust.

Perfect!

I've not used `pixi` before, but if you're already using it then hopefully resolving this won't be too much work

**Comment by jonmmease** [comment]
Yeah, I'll try to add the pixi config soon

**Comment by jonmmease** [comment]
Working on pixi migration in https://github.com/vega/vl-convert/pull/187, but ran into some Rust build issues on CI that I haven't gotten to the bottom of yet.
