### ISSUE TITLE
python: Expose vendored `vega` version string

### ISSUE THREAD

**Issue by dangotbanned** [vega/vl-convert#191]
<details><summary><i>Originally posted by @dangotbanned in <a href="https://github.com/vega/altair/pull/3600#discussion_r1781010865">review</i></summary>
<p>

@mattijn I've settled on the solution here for now:
- [feat: Adds `vl_convert_to_vega_version`, remove `vegalite_to_vega_ver…`](https://github.com/vega/altair/pull/3600/commits/d95a5735c0ae784361529d7d50d558eee5dca7c3)

I'm going to open an issue on https://github.com/vega/vl-convert to see if we can later replace this with a public `vl_convert` function/attribute.
The result would be the same and depend on the same `const`, but would be less reliant on the structure of [vl-convert-vendor/src/main.rs](https://github.com/vega/vl-convert/blob/main/vl-convert-vendor/src/main.rs)

</p>
</details> 

@jonmmease I was wondering if you'd be able to expose the version string component (`"v5.30.0"`) of this under the top level `vl_convert.___`?

https://github.com/vega/vl-convert/blob/65bb8360d9adfe64d0d17d1364005aebec6bf5cd/vl-convert-vendor/src/main.rs#L58

The specific use-case here is to ensure we generate the correct `alt.expr.___` methods, corresponding to a given `vega` release.
My first attempt used the dependencies in `vega-lite`, but this doesn't specify `v5.3.0`
https://github.com/vega/vega-lite/blob/c7697dc293b606ba60c7e374dbf9a77226f91225/package.json#L137-L138

# Related
- https://github.com/vega/altair/pull/3600#discussion_r1781010865

**Comment by jonmmease** [comment]
Hi @dangotbanned, yeah exposing the vendored version numbers makes a lot of sense.
