### ISSUE TITLE
[1.7.0] build fails with undefined references to `ring_core_0_17_8_OPENSSL_ia32cap_P`

### ISSUE THREAD

**Issue by Narrat** [vega/vl-convert#196]
Hi,
trying to build the new release in a container yields the following error in the final stages:

```
   Compiling vl-convert-python v1.7.0 (/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/vl-convert-python)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/usr/lib64/rustlib/x86_64-unknown-linux-gnu/bin:/usr/lib64/rustlib/x86_64-unknown-linux-gnu/bin:/usr/lib64/rustlib/x86_64-unknown-linux-gnu/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustcCD7YBX/list" "-Wl,--no-undefined-version" "-m64" "/tmp/rustcCD7YBX/symbols.o" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/vl_convert.vl_convert.93a93d1738225a3c-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps" "-L" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/gn_out/obj" "-L" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/build/psm-b66315ac3958d658/out" "-L" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/build/libsqlite3-sys-d8353261df3a9f3e/out" "-L" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/build/ring-7f671e62b2efda1b/out" "-L" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/build/libffi-sys-1c26db48e9affdce/out/libffi-root/lib" "-L" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/build/libffi-sys-1c26db48e9affdce/out/libffi-root/lib64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcCD7YBX/libpsm-6ffad7b26216366d.rlib" "/tmp/rustcCD7YBX/liblibffi_sys-aedf2307ca38a807.rlib" "/tmp/rustcCD7YBX/libring-efaac74d4b2f7e03.rlib" "/tmp/rustcCD7YBX/liblibsqlite3_sys-3dd82eaaf8bdc16c.rlib" "/tmp/rustcCD7YBX/libv8-946c846b2592dd37.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-288663704b9edb44.rlib" "-Wl,-Bdynamic" "-ldl" "-lz" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/libvl_convert.so" "-Wl,--gc-sections" "-shared" "-Wl,-soname=libvl_convert.so" "-Wl,-z,relro,-z,now" "-Wl,--strip-all" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/vl_convert.vl_convert.93a93d1738225a3c-cgu.0.rcgu.o: in function `ring::aead::aes::detect_implementation':
          vl_convert.93a93d1738225a3c-cgu.0:(.text._ZN4ring4aead3aes21detect_implementation17h67da5617f565f8e7E+0x7): undefined reference to `ring_core_0_17_8_OPENSSL_ia32cap_P'
          /usr/bin/ld: /home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/vl_convert.vl_convert.93a93d1738225a3c-cgu.0.rcgu.o: in function `ring::aead::gcm::Context::is_avx':
          vl_convert.93a93d1738225a3c-cgu.0:(.text._ZN4ring4aead3gcm7Context6is_avx17h07d5f6bbdc6203a9E+0xe): undefined reference to `ring_core_0_17_8_OPENSSL_ia32cap_P'
          /usr/bin/ld: /home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/vl_convert.vl_convert.93a93d1738225a3c-cgu.0.rcgu.o: in function `ring::aead::gcm::Context::update_blocks':
          vl_convert.93a93d1738225a3c-cgu.0:(.text._ZN4ring4aead3gcm7Context13update_blocks17he719c18460330ad6E+0x80): undefined reference to `ring_core_0_17_8_OPENSSL_ia32cap_P'
          /usr/bin/ld: /home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/vl_convert.vl_convert.93a93d1738225a3c-cgu.0.rcgu.o: in function `ring::aead::gcm::detect_implementation':
          vl_convert.93a93d1738225a3c-cgu.0:(.text._ZN4ring4aead3gcm21detect_implementation17h3ef3324ca6247b1aE+0x7): undefined reference to `ring_core_0_17_8_OPENSSL_ia32cap_P'
          /usr/bin/ld: /home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/vl_convert.vl_convert.93a93d1738225a3c-cgu.0.rcgu.o: in function `ring::aead::aes_gcm::init':
          vl_convert.93a93d1738225a3c-cgu.0:(.text._ZN4ring4aead7aes_gcm4init17he3d53ff88bae905dE+0x113): undefined reference to `ring_core_0_17_8_OPENSSL_ia32cap_P'
          /usr/bin/ld: /home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/target/release/deps/vl_convert.vl_convert.93a93d1738225a3c-cgu.0.rcgu.o:vl_convert.93a93d1738225a3c-cgu.0:(.text._ZN4ring4aead17chacha20_poly130522chacha20_poly1305_seal17h403a856de5067340E+0x48): more undefined references to `ring_core_0_17_8_OPENSSL_ia32cap_P' follow
          /usr/bin/ld: /tmp/rustcCD7YBX/libring-efaac74d4b2f7e03.rlib(c0e3294537cace57-chacha-x86_64-elf.o): relocation R_X86_64_PC32 against undefined hidden symbol `ring_core_0_17_8_OPENSSL_ia32cap_P' can not be used when making a shared object
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `vl-convert-python` (lib) due to 1 previous error
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/usr/bin/python" PYTHON_SYS_EXECUTABLE="/usr/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/omnius/Builds/Maint/Pending/python-vl-convert/src/vl_convert_python-1.7.0/vl-convert-python/Cargo.toml" "--release" "--lib"`
Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/bin/python', '--compatibility', 'off'] returned non-zero exit status 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```

Is there a dep missing on my side? Seems like, although I would have expected not to get this far in that case :D

**Comment by jonmmease** [comment]
Hi @Narrat, thanks for the report.

What architecture container are you using? It looks like pip is pulling down the source distribution of vl-convert-python and attempting to build it from source rather than retrieving one of the pre-compiled binary wheels.  Also, I just published these this morning, so there's a chance that something transitory was going on where the sdist was published but not the binary wheels were not when your container was building.

**Comment by Narrat** [comment]
Thank you for getting back at me.
The container in question is a simple `x86_64` nspawn-container based on Arch.
And the build process itself is a testrun for the respective [AUR package](https://aur.archlinux.org/packages/python-vl-convert) and by naming convention this package should be build from source. Therefore no use of the prebuilt assets from the release page. Additionally the guidelines for python packages also specify the preference for source and not `.whl` files.

But to be sure I will wait some time and try again to build a package.

**Comment by jonmmease** [comment]
Ok, thanks for the context, and yes I understand why you need to build from source. I assume this was working for you prior to version 1.7.0?

This same process for building the source distribution happens for the conda-forge feedstock over in https://github.com/conda-forge/vl-convert-python-feedstock/blob/main/recipe/meta.yaml. So this is possible, but may require some additional system dependencies. OpenSSL is called out in the error, so may be worth investigating what version of openssl is installed in the container and what ring expects.

Here's another arch recipe which reported a similar error mentioning `ring_core_0_17_8_OPENSSL_ia32cap_P`: https://aur.archlinux.org/packages/rsspls. Also here for another AUR build: https://discourse.gstreamer.org/t/video-stream-over-webrtc-has-too-many-artifacts/1767/5.

This issue is also interesting: https://github.com/briansmith/ring/issues/1444. Looks like there is a problem when building ring with link-time-optimization with gcc (rather than clang).  So you could try patching the vl-convert-python to disable link-time-optimization [here](https://github.com/vega/vl-convert/blob/3e806abbb91ed2df43e9b0754ad6deeaf565b547/Cargo.toml#L14).

**Comment by Narrat** [comment]
Yes, it was working before. `1.6.1` was built successfully on 2024-08-24.
I emphasize the date, because your collection of ressources (thank you very much for those) reminded me of something. In august I was still running outdated build flags, which I brought up to date in the meantime.
Therefore I'm currently running the build of `1.6.1` again. Depending on the result one of the links will be chosen as the first candidate.

**Comment by Narrat** [comment]
Ok, `1.6.1` also fails. So it is something independent from `vl-convert`. `openssl` got an update and maybe something is missing a rebuild. Or build flags.
As is doesn't seem to be stemming from `vl-convert` I will close the issue. But I will report back what caused it.
Thank you for your help.

**Comment by Narrat** [comment]
It is because of `LTO`.
With it disabled `1.6.1` was created succesfully. `1.7.0` is currently building but I expect it to succeed

**Comment by jonmmease** [comment]
Great! Does patching to disable LTO work well enough for you for now? I'm not sure if there's a way to make this configurable from the outside.

**Comment by Narrat** [comment]
In general it would work well enough, as it would be rather small change which can be easily followed.
But luckily it isn't necessary to patch. `pacman/makepkg` offer some options and one is `lto/!lto` (with `lto` being the default) which adds `-flto` to the flags.
And [disabling](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-vl-convert&id=32063441f618e213fe58ba209c8484f8416a1b86) it via the options was enough to make the build succeed.
