### ISSUE TITLE
label limit legend 

### ISSUE THREAD

**Issue by mattijn** [vega/vl-convert#30]
Given this python snippet:
```python
import vl_convert as vlc
from IPython.display import Image
vl_spec = '''
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"a": "J", "b": 28, "c": "I am more than 18 characters"},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c"}
  }
}
'''
png_data = vlc.vegalite_to_png(vl_spec=vl_spec)
Image(png_data)
```
Will return the following truncated legend label :
![image](https://user-images.githubusercontent.com/5186265/201373336-30621845-0f23-4b95-b4a9-7da7abf1f826.png)

Where the vega-editor render this as:
![image](https://user-images.githubusercontent.com/5186265/201373556-029873f2-7dec-40f2-8a05-21ee1d51e6d7.png)
And in editor: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoDSABSikEzQAmABxKoaEAEkABEgRuEbAE5w3eiRZNwBGOzdYJF8kKEw4XwMAXwUTZwAhS2tUMTEUtPQAYSy0ABYAZnyQUwAREtQATlCq0wBRertm1OrnADF6sUru0wBxetCGlucACQ6Adin0FwGbJIBdFJBkXwBrZyZoyzhZKDZlGlkyNFAAD2uQADMaOEFlZxQlTABPHDhnWTYCAuOhAmy+9yeLze6Gsnx+f3QAEcGMFMHQ1DRSKDHGxBH4Ic9Xs4nElSUA)

The default `labelLimit` within `legend` is 160 pixels, but this seems not being respected and changing this value has no positive effect on the image.

**Comment by jonmmease** [comment]
Thanks for the report!

**Comment by jonmmease** [comment]
Looking at this a little bit.  When I specify the legend `labelLimit` as below, the full legend is displayed:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"a": "J", "b": 28, "c": "I am more than 18 characters"},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal"},
    "y": {"field": "b", "type": "quantitative"},
    "color": {"field": "c", "legend": {"labelLimit": 250}}
  }
}

```
![wide_text](https://user-images.githubusercontent.com/15064365/210551861-98a8092e-6901-4da3-b500-edfc2da7f009.png)

This is a workaround at least, but I'm still not sure why there's a discrepancy.  In general, the text width measurement matches really well between pure Vega and VlConvert, so I don't think text measurement is that far off.

I am wondering whether Vega's logic for determining whether to perform text truncation somehow ends up using the fallback text width estimation (which is generally larger than a proper measurement), rather than the precise usvg based measurement.

**Comment by jonmmease** [comment]
Another thing I checked. In this case VlConvert's width measurement of the "I am more than 18 characters" string is ~130px.  This matches the width in screen pixels when I display the image at actual size.

![Screen Shot 2023-01-04 at 7 14 37 AM](https://user-images.githubusercontent.com/15064365/210553156-1a0d3250-2e08-4447-a716-2112efbec34e.png)

The tooltip doesn't show up in the screenshot, but this box measures 130x130px.  So, it looks like some number other than this 130px is being compared to the 240px label limit 🤔

**Comment by grwlf** [comment]
Hihi, I see the same issue. Unfortunately, setting `labelLimit=240` or so does not help.

**Comment by jonmmease** [comment]
Vega issue: https://github.com/vega/vega/issues/3715

**Comment by jonmmease** [comment]
Upstream fix proposed in https://github.com/vega/vega/pull/3792
