### ISSUE TITLE
Support ppi argument

### ISSUE THREAD

**Issue by joelostblom** [vega/vl-convert#85]
Vega-Lite 5.8 added support for a `ppi` argument to their CLI in https://github.com/vega/vega-lite/pull/8854. Being able to control the ppi of a figure is quite useful since that would give higher resolution without changing the displayed size (as `scale`/`scale_factor` does). Would it be possible to add a similar `ppi` setting to `vl-convert` so that it could be used both for saving figure and to display figures inline with the `png` renderer?

**Comment by jonmmease** [comment]
I've looked into this a bit, and I think it will depend on https://github.com/image-rs/image-png/pull/403

**Comment by jonmmease** [comment]
Based on https://github.com/vega/vl-convert/issues/84, I'm guessing that a motivation here is to get sharper images when using the Altair PNG renderer.  For this case, we may be able to add something like the `retina` argument to `IPython.display.Image` (https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Image), where the altair PNG renderer would inspec the PNG image and set the display width to half the actual PNG size.

**Comment by jonmmease** [comment]
Try this:

```python
from IPython.display import Image
import vl_convert as vlc

def display_png(chart, scale_factor=1, retina=True):
    if retina:
        scale_factor *= 2
    spec = chart.to_dict(format="vega")
    png = vlc.vega_to_png(spec, scale=scale_factor)
    return Image(png, retina=retina)
```

I think we could do something like this in the Altair PNG renderer, so you would call it like:

```
alt.renderers.enable("png", retina=True)
```

(and we could default to retina `True` of course)

This works in the notebook, but I haven't tried in an exported PDF. Do you want to give that a try?

**Comment by joelostblom** [comment]
Thanks for putting this together. The application I need this for is jupyter books generated with the `--pdflatex` flag. Unfortunately, it seems like the `retina` flag does not have an effect there and images with `retina=True` are not shrunk to half the size and width automatically. This is probably because there is no Jupyter frontend run during the Jupyter Book execution (I think), and this also seems to cause multiple other problems such as Altair charts not showing up with the default HTML renderer and SVGs are [also not working](https://github.com/executablebooks/MyST-NB/issues/370#issuecomment-1636121214), otherwise that would have been a simpler solution. I think it would be great to have a working ppi argument with vl-convert even in context that don't have access to a jupyter frontend (but I also recognize that this wouldn't be as much of an issue if SVG was working in Jupyter Book)

**Comment by jonmmease** [comment]
I tried using the branch in https://github.com/image-rs/image-png/pull/403 with vl-convert, and I was able to generate images with configurable DPI. Here are a few I generated:

### 72 PPI (default)
<img width="366" alt="Screenshot 2023-07-17 at 1 10 11 PM" src="https://github.com/vega/vl-convert/assets/15064365/4f66a10b-60e4-49e5-ba99-0ce03bb23afa">

![circle_binned](https://github.com/vega/vl-convert/assets/15064365/a8fb5685-928d-46eb-b9f0-1effcb4cfa83)

### 127 PPI
<img width="366" alt="Screenshot 2023-07-17 at 1 11 01 PM" src="https://github.com/vega/vl-convert/assets/15064365/b625a599-2166-4bc6-acaa-c2d6ef654999">

![circle_binned copy 2](https://github.com/vega/vl-convert/assets/15064365/0132599c-11d8-4a68-84fa-8c53905b8375)

But the apple preview inspector is the only place I saw a difference in behavior. For example, GitHub renders them the same size.

I'm not sure what PNG rendering environments honor the PPI property. Have you looked into this?  Do you want to try the two images above in Jupyter Book to see if they render with different sizes?

**Comment by joelostblom** [comment]
Hmm I don't see any difference with your two images but if I create two new images of 10 dpi and 100 dpi, I do see differences. Here are the two source images:

10
![10](https://github.com/vega/vl-convert/assets/4560057/c9719288-f7f8-4dd6-9115-f4cd95502784)

100
![100](https://github.com/vega/vl-convert/assets/4560057/365bf50d-86bf-4f6e-83eb-ab378d6920c3)

Here is how they show up in JupyterLab:

![image](https://github.com/vega/vl-convert/assets/4560057/0a8f89f6-7a4b-4f2c-a345-ae0ee7aa70de)

Here is how they show up in Jupyter Books PDF Latex output:

![image](https://github.com/vega/vl-convert/assets/4560057/adfc50d6-4721-4fab-a26f-b3908ab38033)

**Comment by joelostblom** [comment]
I'm not on a Mac so  Ican't see what ppi is reported by Preview for those images but they seem to have the correct density based on running this command from the terminal:

```
identify -units PixelsPerInch -format '%[fx:int(resolution.x)]\n' 100.png
```

Although it seems like their reported size is also different, so I'm a bit confused about why both the size and the ppi differ.

**Comment by jonmmease** [comment]
Here's what these two look like in the preview inspector

10
<img width="366" alt="Screenshot 2023-07-17 at 4 32 28 PM" src="https://github.com/vega/vl-convert/assets/15064365/8c185b9f-6259-4239-8367-ff42e2fb0fe7">

100
<img width="366" alt="Screenshot 2023-07-17 at 4 33 10 PM" src="https://github.com/vega/vl-convert/assets/15064365/09417e25-c70d-4055-9307-0a0651bdddc3">

**Comment by jonmmease** [comment]
Just to make sure I'm following...

Based on your experiments above, it looks like Jupyter in the browser doesn't care about PPI, just pixels.  But the PdfLatex output uses it to convert pixels to image size. 

But, when you tried using my 76 and 127 PPI images with PdfLatex they both came out the same size in the resulting PDF? (I would have hoped that the 127 PPI image would turn out smaller).

**Comment by joelostblom** [comment]
> But, when you tried using my 76 and 127 PPI images with PdfLatex they both came out the same size in the resulting PDF? (I would have hoped that the 127 PPI image would turn out smaller).

Yeah, this is odd, when I run you two images in jupyter book it looks like this:

![image](https://github.com/vega/vl-convert/assets/4560057/df26da25-b89f-4bd4-80e2-e98f42ac79fe)

What's also odd to me is that the smaller 72 ppi file seems larger at 19KB compared to the 127 ppi file (16KB). And when I run the `identify` command they both show `0` for `PixelsPerInch` and when I look at them by eye, I can't see a different in resolution. The comment here https://github.com/vega/vega-lite/pull/8854#issuecomment-1518451087 makes it seem like the PixelsPerInch (or Meter) needs to be set and it seems like it is maybe not set correctly on these images although the report a ppi?

**Comment by jonmmease** [comment]
I went back and regenerated three images more carefully. All 3 have scale=1 so all three have 360 x 247 pixels. The only thing that changes is the PPI:

#### 10 ppi
![circle_binned_10ppi](https://github.com/vega/vl-convert/assets/15064365/b379bce5-3949-48ea-b9e7-180cd2024cca)

#### 100 ppi
![circle_binned_100ppi](https://github.com/vega/vl-convert/assets/15064365/3b5cad50-05a2-48a9-87e1-8350523b4089)

#### 200 ppi
![circle_binned_200ppi](https://github.com/vega/vl-convert/assets/15064365/d9b6b4fe-2151-41e7-97db-111a8cc51cd1)

### identify
The expected PPI shows up in the MacOS preview inspector and with the imagemagick `identify` CLI:
```
% identify -units PixelsPerInch -format '%[fx:int(resolution.x)]\n' ./circle_binned_10ppi.png 
10
% identify -units PixelsPerInch -format '%[fx:int(resolution.x)]\n' ./circle_binned_100ppi.png 
100
% identify -units PixelsPerInch -format '%[fx:int(resolution.x)]\n' ./circle_binned_200ppi.png 
200
```

Could you try running these three though Jupyter Book Latex PDF? We'd expect `circle_binned_10ppi.png` to be giant, `circle_binned_100ppi.png` to be about 3.6" across, and `circle_binned_200ppi.png` to be about 1.8" across.

If these all look the same in the LaTeX PDF output, I'm not sure what to try next 😕

**Comment by joelostblom** [comment]
Awesome thank you! These work as expected!!

![image](https://github.com/vega/vl-convert/assets/4560057/06c6c236-9414-437e-8dee-866cdf80ad57)

**Comment by joelostblom** [comment]
So after https://github.com/image-rs/image-png/pull/403 has been merged, would vl-convert and/or altair need updates as well or does it pass through additional parameter so that the png renderer could take a `ppi` argument  as is? I wonder if it would be confusing that the images don't change resolution in JupyterLab, but I guess we could remedy that by noting it in the documentation

**Comment by jonmmease** [comment]
> Awesome thank you! These work as expected!!

🎉  I'll follow up on that PR. I don't have a good way of doing a full vl-convert release against a git branch of a dependency, but we can get started at least.

Would it be helpful to you to have a dev build ASAP for working on the book?

**Comment by joelostblom** [comment]
Great, thank you! Yes it would be helpful with a dev build for the book I'm working on, but I don't think it needs to be ASAP so whenever you get the chance to put one up then that's good for me. Thanks for exploring this and working out what was going on!

What do you think is the best solution for the fact that different contexts seem to handle interpret ppi attribute of PNG files differently? Both GitHub and JupyterLab seem to show the images as the same size, so is jupyter book the odd one out here? I guess since Jupyter supports SVG, it would be easy to recommend that format for seeing higher resolution image in jupyter book itself, and maybe this ppi option is mostly for saving/exporting image to PNG files as well as including them in contexts that don't support SVG, such as Jupyter Book with Latex

**Comment by jonmmease** [comment]
Sounds good. I'll keep you posted.

Regarding displaying in Jupyter, I wonder if we could use a generalization of the `retina` trick above to achieve the same effect as what happens in Jupyter Book / LaTeX.

**Comment by jonmmease** [comment]
> So after https://github.com/image-rs/image-png/pull/403 has been merged, would vl-convert and/or altair need updates as well or does it pass through additional parameter so that the png renderer could take a ppi argument as is?

Sorry, I missed this question. Yeah, vl-convert will need a new release to update this dependency and add the `ppi` kwarg to the `vlc.*_to_png` functions.  Then we will need to update the PNG renderer in Altair to take a `ppi` argument and pass it through to vl-convert (if vl-convert is a new enough version).  Ideally, the Altair PNG renderer would also include logic similar to the `retina` flag in `IPython.display.Image` to make the image appear to be the same size as it will in the PDF export, but I don't have a good sense yet of how complex that will be.
